export const EXCEPTION_CODES = {
  BAD_REQUEST: 'BAD_REQUEST',
  REQUIRED_FIELD: 'REQUIRED_FIELD',
  INVALID_LENGTH: 'INVALID_LENGTH',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_FORMAT: 'INVALID_FORMAT',
  INVALID_VALUE: 'INVALID_VALUE',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  ANIMAL_NOT_FOUND: 'ANIMAL_NOT_FOUND',
} as const;
