export const EXCEPTION_CODES = {
  REQUIRED_FIELD: 'REQUIRED_FIELD',
  INVALID_LENGTH: 'INVALID_LENGTH',
  INVALID_EMAIL: 'INVALID_EMAIL',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;
